version: '3.1'
services:
  app-storage:
    volumes:
      - "codevolume:/usr/src/ptdls"
    build: ./

  nginx-backend:
    image: nginx:1.18.0-alpine@sha256:29dc24ed982665eb88598e0129e4ec88c2049fafc63125a4a640dd67529dc6d4
    ports:
      - 8000:80
    links:
      - 'app-storage'
      - 'php'
    volumes:
      - "codevolume:/usr/src/ptdls"
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - 'app-storage'
  php:
    image: php:7.4-fpm-alpine3.12@sha256:4c67c85bacbdada12f8ad56888fb6d21c7864f9373d08e804bd66ab19dc9ba24
    volumes:
      - "codevolume:/usr/src/ptdls"

volumes:
  codevolume: